version: '3.6'
services:
  api:
    image: node:14.8.0-stretch
    container_name: ac-node
    build: .
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=8080
      - ELASTIC_URL=http://elasticsearch:9200
    volumes: # mount a volume
      - .:/usr/src/app/autocomplete
    command: npm run dev
    links:
      - elasticsearch
    depends_on: # start api service after elasticsearch service has booted
      - elasticsearch
    networks:
      - esnet # make api and elasticsearch share same network so they can call each other w/ same ports

  elasticsearch:
    container_name: ac-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none # cut off verbose logs
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - esnet
volumes:
  esdata:
networks:
  esnet: